# Generated by Django 3.1 on 2020-08-08 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialpages', '0002_auto_20200808_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('post', models.TextField()),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='socialpages.editor')),
                ('tags', models.ManyToManyField(to='socialpages.tags')),
            ],
        ),
    ]
