# Generated by Django 3.1 on 2020-08-09 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialpages', '0005_post_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostRecipients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
    ]
