# Generated by Django 3.1 on 2020-08-09 13:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('socialpages', '0006_postrecipients'),
    ]

    operations = [
        migrations.AddField(
            model_name='postrecipients',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
    ]
