# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-11 13:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('socialpages', '0007_postrecipients_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='editor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='post',
            field=tinymce.models.HTMLField(),
        ),
        migrations.DeleteModel(
            name='Editor',
        ),
    ]
